### ISSUE TITLE
xsolla could support SAAS / Application Development?

### ISSUE THREAD

**Issue by meteorsnows** [xsolla/xsolla-login-js-sdk#24]
Xsolla maybe have a legal team to make it a "payment service" for game. But actually i am consider the Login service + Subscription actually quite good enough for subscription model SAAS that maybe with niche area. So would ask if there is chance that Xsolla extend the service to all kinds of developer.

**Comment by Vortsvord** [comment]
Hi! 
This is in the plans for next year. 
All changes can be monitored on the corporate website (xsolla.com)  and developer changelog (developers.xsolla.com/ru/changelog/) or contact the account managers of the company
