### ISSUE TITLE
XL.show() shows modal. Is there XL.close() or similar?

### ISSUE THREAD

**Issue by seanmavley** [xsolla/xsolla-login-js-sdk#26]
After I show a modal, how do I close it if I want to?

By removing it from the DOM via jquery or something? Or xsolla comes with its own way to hide/close the modal when open

**Comment by Vortsvord** [comment]
Hello.
We do not have such a function for SDK. The widget is closed by the user by clicking on the cross.
You can try the XL._hide() function. The block with the widget will be hidden.

**Comment by seanmavley** [comment]
Good to know. Thanks.
